### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [dfaker/VR-reversal#10]
Hi, good work.

I've been playing with this code in a private repo for a long time, but it's unclear what I can legally do with it. Your very old commits work better for me. At one point it was working with --hwdec too, but something changed in FFmpeg I suppose.

It's a shame that FFmpeg is so slow. I couldn't really come up with much on that front.

I think that one thing people don't realize or notice when they have issues is that many cards don't work well with videos larger than 4096x4096, so re-encoding beforehand is always an option.

**Comment by dfaker** [comment]
Anyhting you'd care to #11

**Comment by ghost** [comment]
Great, thanks!
