### ISSUE TITLE
Getting Lua Error when running the script

### ISSUE THREAD

**Issue by openwick** [dfaker/VR-reversal#12]
Hi I am running fedora 35 and I downloaded both lua and .conf and kept them in `.config/mpv/scripts` folder and ran the readme command from the readme `mpv --script=360plugin.lua --script-opts=360plugin-enabled=yes file.mp4` where the video is and I am getting the following error.

```Can't load unknown script: /home/wick/.config/mpv/scripts/360plugin.conf
[file] Cannot open file '360plugin.lua': No such file or directory
Failed to open 360plugin.lua.
[360plugin] 
[360plugin] stack traceback:
[360plugin] 	[C]: ?
[360plugin] 	[C]: ?
[360plugin2] 
[360plugin2] stack traceback:
[360plugin2] 	[C]: ?
[360plugin2] 	[C]: ?
[360plugin2] Lua error: [string "/home/wick/.config/mpv/scripts/360plugin.lua"]:563: '=' expected near 'continue'
[360plugin] Lua error: Could not read file.
[360plugin] 
 (+) Video --vid=1 (*) (h264 1440x720 59.940fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
```

Video is playing after this error in a side by side format.
I tried running the command by placing the lua script in the video folder but got the same lua error.
Any idea what I am doing wrong or how to fix this issue?

**Comment by dfaker** [comment]
If you have placed the lua script in your scripts directory then it'll be auto loaded, no need to also pass the `--script` or `--script-opts` parameters, simply press 'v' to switch on the vr-reversal mode.

**Comment by openwick** [comment]
yes I kept the lua file and conf file in scripts folder and I run it wiith `mpv filename.mp4` now. Still getting this error

```mpv file.mp4 
Can't load unknown script: /home/wick/.config/mpv/scripts/360plugin.conf
[360plugin] 
[360plugin] stack traceback:
[360plugin] 	[C]: ?
[360plugin] 	[C]: ?
[360plugin] Lua error: [string "/home/wick/.config/mpv/scripts/360plugin.lua"]:563: '=' expected near 'continue'
 (+) Video --vid=1 (*) (h264 1440x720 59.940fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1440x720 yuv420p
AV: 00:00:11 / 00:44:37 (0%) A-V:  0.000 Dropped: 7 Cache: 265s/150MB

```

**Comment by dfaker** [comment]
I don't use the script opts but I think the conf file just goes in a the `/home/wick/.config/mpv/script-opts` folder or omit it entirely.

Otherwise line 563 in 360plugin.lua looks perfectly fine to me, and doesn't contain an `=` in the repo are we certain it's a fresh accurate copy?

**Comment by glubsy** [comment]
@openwick what version of mpv are you running? 

I have not looked into it further, but perhaps something changed in the expected lua syntax.

**Comment by openwick** [comment]
@glubsy I am user 0.34 here is the full info

``` mpv --version
mpv 0.34.0 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1

```
still the script is not working

**Comment by glubsy** [comment]
It really seems like the lua parser has had some kind of patch applied to it. 
What operating system is this? Can you post the lua version installed (type `lua -v`)? 

You could try changing these lines to this, and it might work: 
line [563](https://github.com/dfaker/VR-reversal/blob/11464f8c547ed07d1008d2ede6fd24632161f86c/360plugin.lua#L563) and line [584](https://github.com/dfaker/VR-reversal/blob/11464f8c547ed07d1008d2ede6fd24632161f86c/360plugin.lua#L584): change `goto continue` to `continue`,
line [570](https://github.com/dfaker/VR-reversal/blob/11464f8c547ed07d1008d2ede6fd24632161f86c/360plugin.lua#L570) and line [587](https://github.com/dfaker/VR-reversal/blob/11464f8c547ed07d1008d2ede6fd24632161f86c/360plugin.lua#L587): delete the line with `::continue::`.

Even then it might not really work and you'll get another error. This [online](https://fptje.github.io/glualint-web/) checker initially gave me error `Line 563:  unexpected continue expecting indexation or function call`, but after I removed the goto statements and kept only "continue", oddly enough the errors disappeared.  

In lua 5.4 here on Arch Linux, by toying around with this simple test I got `syntax error near 'end'` at line 6:
```lua
i = 0
while i < 20 do
        i = i + 1
        if i % 2 == 0 then
                continue
        end
end
```
Whereas the usual `goto` + `::label::` version works just fine. 

I'm not sure how lua is implemented in mpv, but it seems they are using the lua headers from the operating system. So either you are running a patched version of lua, or mpv has some kind of patch going on. Not sure yet.

**Comment by openwick** [comment]
HI @glubsy sorry for the late reply. 
I am running lua version 5.4.3 on Fedora 35 as the output of `lua  -v` is this
```$ lua -v
Lua 5.4.3  Copyright (C) 1994-2021 Lua.org, PUC-Rio
```
I changed the lines as you mentioned but I am getting the same error. Still getting the same error 

`[360plugin] Lua error: [string "/home/wick/.config/mpv/scripts/360plugin.lua"]:564: '=' expected near 'end'`

Just for reference here are those for loops from 560 to 590 with changes as you mentioned. I also moved the `continue` one tab inside just to see if it works but it didn't :(

```
local restore_props = function()
	for k, v in pairs(saved_props) do
		if v == "NIL" then
			continue
		end
		if k == "hwdec" then
			-- Can also be displayed in osd console with "show-text ${hwdec-current}"
			mp.osd_message(string.format("Restoring hardware acceleration: %s", v), 1.5)
		end
		mp.set_property(k, v)
	end

	for k, _ in pairs(saved_props) do
		saved_props[k] = "NIL"
	end
end

local restore_keybinds = function()
	-- There is no need to re-apply the previous key-bindings if they have been
	-- forcibly rebound by our script. They are still there after removal.
	for k,v in pairs(bindings) do
		if k == binding_by_name("toggle_vr360") then
			print("Keeping key bind to toggle vr360: " .. k)
			continue
		end
		mp.remove_key_binding(v["name"])
	end
end
```

**Comment by dfaker** [comment]
> Even then it might not really work and you'll get another error. This [online](https://fptje.github.io/glualint-web/) checker initially gave me error `Line 563: unexpected continue expecting indexation or function call`, but after I removed the goto statements and kept only "continue", oddly enough the errors disappeared.

`continue` isn't a keyword in standard lua, glualint is a validator for a specific variant of lua used in the half-life mod 'gmod' which rather unluckily does include a `continue` keyword but even their own docs advise against using it https://wiki.facepunch.com/gmod/Specific_Operators .

Your original goto label method seems to be the best way in standard lua.

**Comment by glubsy** [comment]
> glualint is a validator for a specific variant of lua used in the half-life mod 'gmod'

@dfaker ah, that makes sense. Shame on me for not noticing that. Thanks for the heads-up.

**Comment by dfaker** [comment]
Could not reproduce, all indications are an issue with the lua interpreter in the users mpv build.
