### ISSUE TITLE
[Feature request] 3D SBS/TAB output 

### ISSUE THREAD

**Issue by daitj** [dfaker/VR-reversal#13]
I would like to watch SBS 360 video in my 3D TV with controller (mouse input),
So if this plugin could show the output of right eye and left eye, side by side, I could use that to watch it in 3D. 

May be another use case would be to able to stream it to phone to watch in cardboard VR with sunshine-moonlight (+opentrack) combo.

**Comment by dfaker** [comment]
I'm not quite understanding what you're requesting: this is a plugin for the mpv media player, if the platform, such as your television can't run mpv then this is a non-starter.

**Comment by daitj** [comment]
I have hooked my TV via HDMI to my PC . My TV can convert SBS video to 3D and I can watch them using 3D glasses. I want to be able to watch 360 videos in 3D in my TV using mpv, I want to be able to look around in 360 video (move around) using mouse.

I hope you get what I mean.

**Comment by dfaker** [comment]
Hmm, The filter may already work for you, would you mind conducting a test with this branch which is set to produce side by side output:

https://github.com/dfaker/VR-reversal/tree/dfaker-sbs-output-test

We may also need to do some aspect ratio squashing but let me know how this output looks.

**Comment by daitj** [comment]
Amazing, it works. But like you mentioned, aspect ratio is bit off,  the black bars on top and bottom are too large, may be exactly double to what we have in 2d mode.

**Comment by dfaker** [comment]
Okay try that now, `p` toggles the side by side output mode and sets a half width scaling on the output.

**Comment by daitj** [comment]
For TV it works perfectly, because TV automatically stretches each side to full 1080p.

Watching it in cardboard vr, it was too squeezed horizontally. setting `sarOutput = 0.75` does fix that, but then there is black bars on top and bottom.

**Comment by dfaker** [comment]
In cardboard vr, is it just streaming your captured screen? or are you writing it to a file?

**Comment by daitj** [comment]
I am streaming the window capture.  It is for using powerful PC to process high quality videos and streaming to lowend phone. I tried playing the files with VR players in my phone, the playback is really bad.

**Comment by dfaker** [comment]
Just trying to work out if the phone is getting any additional aspect ratio information via metadata in a file.
The 0.75 squash factor doesn't seem reasonable to include as a feature whereas as the 0.5 seems a perfectly reasonable way to restore the doubled frame to the correct shape as expected by 3d video apps (and indeed the ffmpeg anaglyph filters).

This is now merged into the main branch, have fun!
