### ISSUE TITLE
Please remove forced toggle keybinding and maybe change the default toggle keybinding

### ISSUE THREAD

**Issue by microraptor** [dfaker/VR-reversal#16]
Please change line 723 from:
`			mp.add_forced_key_binding(k, "toggle_vr360", v["fn"])`
to:
`			mp.add_key_binding(k, "toggle_vr360", v["fn"])`
So that the keybinding is not forced.

Then in mpv's `input.conf` v can be reused and the toggle can be reassigned to something else like this:
```
v cycle sub-visibility 
b script-binding 360plugin/toggle_vr360
```
Currently the v-key can only toggle vr360, when the script is loaded. Which is not very optimal, since it is assigned by default to toggling subtitle visibility and quite important.

I would also suggest assigning the vr_360 toggle keybinding to something else that is not used by mpv's defaults:
https://github.com/mpv-player/mpv/blob/master/etc/input.conf

**Comment by dfaker** [comment]
Please feel free to edit your local version of `script-opts/360plugin.conf` to set the bindings to whatever you find most usable.
