### ISSUE TITLE
Strech the width on SBS video but keep same height

### ISSUE THREAD

**Issue by daitj** [dfaker/VR-reversal#20]
How can I strech the width of the video in SBS mode. 

I tried to play around with MPV's video-scale-* (x/y) but this streches whole output not each sides?

I tried to change sarOutput but this changes the height, which is not useful. 

What value do I need to pass to ffmpeg to acheive this?

**Comment by dfaker** [comment]
Do none of the modes with the P key work?

If you're using ffmpeg directly you can try passing through https://ffmpeg.org/ffmpeg-filters.html#stereo3d there's a few output modes there for half and full width outputs.

**Comment by daitj** [comment]
I am specifically talking about sbs-hw mode (using P key), I have a weird need where I need to stretch width for it to look good enough, but I cannot seem to find a way to do it.  

It is okay if you do no want to spend your time with this or do not know about this enough. I will try to do some more research myself.

**Comment by dfaker** [comment]
Do we have a screenshot of a representative frame from the initial video before any processing?

I'll see how the modes under the P key could be extended to accommodate it.

**Comment by daitj** [comment]
Sorry to reopen this old thread, I came back with a video (180 degree SBS 3D VR) 

This is screenshot of the video without VR-reversal:
![video](https://github.com/dfaker/VR-reversal/assets/682274/28dc3dbd-ae29-4ceb-9789-e77a224fb801)


Currently it looks like this on "SBS half width mode" using VR-reversal, The horizontal view(width) each side is squeezed, when you look this through VR googles (cardboard vr).  
![vr-reversal](https://github.com/dfaker/VR-reversal/assets/682274/2d4ee0cc-6028-4906-812f-2cb86689d835)


This is how I want it to look like, which is the default implementation in this [project](https://github.com/sandsmark/linux-vr-player-or-something)
![linux-vr-player](https://github.com/dfaker/VR-reversal/assets/682274/6a035305-85e3-4aac-8932-b180304aa65f)


[Video](https://www.youtube.com/watch?v=JDE2nfczRl0) from the example
