### ISSUE TITLE
How about the same thing for OU/TAB videos?

### ISSUE THREAD

**Issue by netExtra** [dfaker/VR-reversal#32]
Can this script be used for Top/Bottom videos? If not then can it be modified?

Thanks.

**Comment by dfaker** [comment]
by default `r` switches between sbs and tb modes.

**Comment by netExtra** [comment]
Excellent. I spent a few minutes playing with it then properly looked at your code. I made TB the default and started with res=5 for performance with larger files. With a bit of practice it works pretty good in VR too  :)
