### ISSUE TITLE
v360 filter update extremely slow when video is paused

### ISSUE THREAD

**Issue by riaqn** [dfaker/VR-reversal#8]
When the video is paused and I try to move my camera, or adjust projection settings, the picture is updated very slowly; I can observe a roughly 1 sec delay. Usually the delay is around 0.2s.

This is a mpv problem in general I believe - I wrote a python program using [python-mpv](https://github.com/jaseg/python-mpv) that also uses v360 to play vr video on computer, and suffer the same issue.

I certainly don't expect you to fix a problem that wasn't yours to begin with, but just wondering if you know any workaround of this?

**Comment by dfaker** [comment]
Yeah I think that's a limitation on how often mpv choses to update when paused. certainly if it doesn't change significantly when something like interp=near is set I think it's safe to assume mpv simply isn't pushing frames through the filter so nothing is changing.

**Comment by riaqn** [comment]
Thank you, I have submitted issue to mpv: https://github.com/mpv-player/mpv/issues/9049
