### ISSUE TITLE
New versions of ffmpeg have altered their api to interpret rotations sent via sendcmd as relative by default

### ISSUE THREAD

**Issue by dfaker** [dfaker/VR-reversal#9]
lerp(x,y,z) against these directly is not possible, so some creativity will be needed to get smooth head motions working on later versions.

Passing of the reset_rot flag (to 1, once, during initialization) and sending of all of the rotations (during each time step) will be required.

**Comment by richardpl** [comment]
This is an invalid statement.

**Comment by dfaker** [comment]
> This is an invalid statement.

You forget we live in a spatio-temporal world.

**Comment by richardpl** [comment]
There is option to reset your spatial only funcionality by just setting reset_rot=1 once at beginning.

**Comment by dfaker** [comment]
Thank you, I didn't plan to go into the calling conventions here, but that's a nice fact.

**Comment by richardpl** [comment]
And it doesn't any more resets yaw/pitch/roll with that option set.

**Comment by dfaker** [comment]
I am surprised to hear that, thank you for letting me know.

**Comment by dfaker** [comment]
Works on bleeding edge ffmpeg and mpv now, a couple of the right lines over in ffmpeg and a couple of characters here.
